create table usuario (
        data_atualizacao timestamp(6) with time zone,
        ident bigint generated by default as identity,
        usuario varchar(30),
        senha varchar(25),
        email varchar(75),
        primary key (ident)
    )