create table conta (
        saldo numeric(38,2),
        data_atualizacao timestamp(6) with time zone,
        data_criacao timestamp(6) with time zone,
        ident bigint generated by default as identity,
        nome_conta varchar(255),
        numero_conta varchar(255),
        primary key (ident)
    )