create table movimentacao_conta (
        saldo_atual_conta numeric(38,2),
        valor_movimentado numeric(38,2),
        data_movimentacao timestamp(6) with time zone,
        id_conta bigint,
        ident bigint generated by default as identity,
        descricao varchar(255),
        tipo_despesa enum ('TP_ALIMENTACAO','TP_ANIMAIS','TP_EDUCACAO','TP_INVESTIMENTO','TP_LAZER','TP_OUTROS','TP_SAUDE','TP_SEGUROS','TP_TRANSPORTE','TP_VIAGEM'),
        tipo_movimentacao enum ('MOV_ENTRADA','MOV_SAIDA'),
        primary key (ident)
    );
    
alter table if exists movimentacao_conta 
       add constraint FKp145twoyxgwxf1cqjvqd075qi 
       foreign key (id_conta) 
       references conta;