create table conta (
		ident bigint generated by default as identity,
        saldo numeric(38,2),
        data_atualizacao timestamp(6) with time zone,
        data_criacao timestamp(6) with time zone,
        nome_conta varchar(255),
        numero_conta varchar(255),
        id_usuario BIGINT,
        primary key (ident),
        CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (ident)
    )