create table movimentacao_conta (
        saldo_atual_conta numeric(38,2),
        valor_movimentado numeric(38,2),
        data_movimentacao timestamp(6) with time zone,
        id_conta bigint,
        ident bigint generated by default as identity,
        descricao varchar(255),
        tipo_despesa tipo_despesa_enum,
        tipo_movimentacao tipo_movimentacao_enum,
        primary key (ident)
    );
    
alter table if exists movimentacao_conta 
       add constraint FKp145twoyxgwxf1cqjvqd075qi 
       foreign key (id_conta) 
       references conta;